name: self-test

on:
  push:
    branches: [main, test-me-*]
    tags:
  pull_request:

jobs:
  fast-checkout:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/fast-checkout
      with:
        path: subdir
