on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      env:
        required: true
        type: string
      arch:
        required: false
        type: string
        default: '[""]'
      wheel-tags:
        required: false
        type: boolean
        default: false
      submodules:
        required: false
        type: boolean
        default: false

jobs:
  tox:
    name: ${{ inputs.os }} / ${{ matrix.env }}${{ inputs.arch != '[""]' && format(' /  {0}', matrix.arch) || '' }}
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        env: ${{ fromJSON(inputs.env) }}
        arch: ${{ fromJSON(inputs.arch) }}
    steps:
    - uses: asottile/workflows/.github/actions/fast-checkout@v1.8.0
      with:
        submodules: ${{ inputs.submodules }}
    - uses: actions/setup-python@v4
      with:
        python-version: |
          ${{
            (matrix.env == 'pypy3' || startsWith(matrix.env, 'pypy3-')) && 'pypy3.10' ||
            (matrix.env == 'py39' || startsWith(matrix.env, 'py39-')) && '3.9' ||
            (matrix.env == 'py310' || startsWith(matrix.env, 'py310-')) && '3.10' ||
            (matrix.env == 'py311' || startsWith(matrix.env, 'py311-')) && '3.11' ||
            (matrix.env == 'py312' || startsWith(matrix.env, 'py312-')) && '3.12' ||
            '3.13'
          }}
        architecture: ${{ matrix.arch }}
      if: |
        ${{
          matrix.env != 'py314' && !startsWith(matrix.env, 'py314-')
        }}
    - uses: deadsnakes/action@v3.0.1
      with:
        python-version: 3.14-dev
      if: matrix.env == 'py314' || startsWith(matrix.env, 'py314-')
    - uses: ./.github/actions/pre-test
      if: ${{ hashFiles('.github/actions/pre-test/action.yml') != '' }}
    - run: python -mpip install --upgrade setuptools tox virtualenv
    - run: tox -e ${{ matrix.env }}
    - name: build wheels
      run: |
        set -x

        if [ '${{ runner.os }}' = 'Windows' ]; then
          bin='.tox/${{ matrix.env }}/Scripts'
        else
          bin='.tox/${{ matrix.env }}/bin'
        fi

        # disable universal2 wheels
        if [ '${{ runner.os }}' = 'macOS' ]; then
          if [ '${{ runner.arch }}' == 'ARM64' ]; then
            export _PYTHON_HOST_PLATFORM='macosx-11.0-arm64'
            export ARCHFLAGS=""
          else
            export _PYTHON_HOST_PLATFORM='macosx-10.9-x86_64'
            export ARCHFLAGS=""
          fi
        fi

        "$bin/pip" wheel --no-deps --wheel-dir wheels .

        if [ '${{ runner.os }}' = 'macOS' ]; then
          "$bin/pip" install 'delocate>=0.10.3'
          "$bin/delocate-wheel" wheels/*.whl
        fi
      shell: bash
      if: inputs.wheel-tags && github.ref_type == 'tag'
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ inputs.os }}-${{ matrix.env }}-${{ matrix.arch }}
        path: wheels/*.whl
      if: inputs.wheel-tags && github.ref_type == 'tag'

  collector:
    needs: [tox]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: check for failures
      if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: echo 'dependent job failed' && exit 1
    - uses: actions/upload-artifact/merge@v4
      with:
        name: wheels-${{ inputs.os }}
        pattern: wheels-${{ inputs.os }}-*
        delete-merged: true
      if: inputs.wheel-tags && github.ref_type == 'tag'
